events {}

http {
    log_format netlab '$remote_addr - $request_id [$time_local] "$request" '
                      '$status $body_bytes_sent upstream=$upstream_addr '
                      'upstream_time=$upstream_response_time request_time=$request_time';

    upstream api_pool {
        least_conn;
        server backend_a:8000 max_fails=2 fail_timeout=5s;
        server backend_b:8000 max_fails=2 fail_timeout=5s;
        keepalive 32;
    }

    server {
        listen 80;
        access_log /var/log/nginx/access.log netlab;

        location = /nginx-health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 'nginx-ok\n';
        }

        location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Request-ID $request_id;
            proxy_connect_timeout 1s;
            proxy_read_timeout 4s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
            proxy_pass http://api_pool;
        }
    }
}
